name: Deploy to GitHub Pages

on:
  push:
    branches:
      - production
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies (React Vite)
        working-directory: ./frontend 
        run: |
          npm install

      - name: Build Frontend
        working-directory: ./frontend
        run: |
          npm run build

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Composer Dependencies (Laravel)
        working-directory: ./backend
        run: |
          composer install --no-dev --prefer-dist

      - name: Build and Optimize Laravel Assets
        working-directory: ./backend
        run: |
          php artisan optimize
          
      - name: Debug Artifact Contents
        run: |
          ls -R ./frontend/dist

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          path: ./frontend/dist

      - name: Debug Artifact Contents After Upload
        run: |
          ls -R ./frontend/dist

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          publish_dir: ./frontend/dist
          commit_message: "Deploy to GitHub Pages"
