name: Deploy to GitHub Pages

on:
  push:
    branches:
      - production
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies (React Vite)
        working-directory: ./frontend
        run: |
          npm install

      - name: Build Frontend
        working-directory: ./frontend
        run: |
          npm run build

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Composer Dependencies (Laravel)
        working-directory: ./backend
        run: |
          composer install --no-dev --prefer-dist

      - name: Build and Optimize Laravel Assets
        working-directory: ./backend
        run: |
          php artisan optimize

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: frontend-dist
          path: ./frontend/dist

      - name: Debug Artifact Contents
        run: |
          ls -alR ./frontend/dist
          find ./frontend/dist -type l

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          timeout: 600000
          error_count: 10
          reporting_interval: 5000
          artifact_name: frontend-dist
          preview: false
        env:
          COMPOSER_PROCESS_TIMEOUT: 0
          COMPOSER_NO_INTERACTION: 1
          COMPOSER_NO_AUDIT: 1
